### PR TITLE
Ready: Rename float, integer, and binary to double, sint64, and varchar for column type info.

### PR DESCRIPTION
**Pull request by alexmoore**
Coincides with these PRs:
https://github.com/basho/riak_ql/pull/36
https://github.com/basho/riak_kv/pull/1247
https://github.com/basho/eleveldb/pull/167
https://github.com/basho/riak_test/pull/915

### CODE REVIEW

**Comment by Basho-JIRA** [comment]
PR for this is https://github.com/basho/riak_pb/pull/153 

***[posted via JIRA by Alexander Moore]***

**Comment by Basho-JIRA** [comment]
Ok [~lbakken], you can review this instead :) 

***[posted via JIRA by Alexander Moore]***

**Comment by hmmr** [comment]
Those .idea/* files should probably not be there (I suggest rebase and force-push rather than another commit deleting them).

**Comment by lukebakken** [comment]
These changes seem fine to me, we'll see if `bigint` is accepted or not :shipit:

**Comment by lukebakken** [comment]
+1 d9fbaa45b93efb9c06bfe2254e6ff20f5deb101b

**Comment by alexmoore** [comment]
@borshop merge

**Comment by DSomogyi** [comment]
RTS-524

**Comment by lukebakken** [comment]
@borshop merge

**Pull request merged**
