### PR TITLE
optionally support streaming for list_keys

### PR DESCRIPTION
**Pull request by hmmr**
A me-too PR hot on the heels of #167 (RIAK-2080).

### CODE REVIEW

**Comment by javajolt** [comment]
This seems to make sense

**Comment by javajolt** [comment]
:+1: 7344d74

**Comment by jonmeredith** [comment]
Thanks for thinking about this too Andrei.

Aren't the list keys requests streaming by default? I did the other PR because it was *not* streaming by default and we want to add it in future.

Presumably the clients already have streaming support for TS listkeys?

**Comment by alexmoore** [comment]
If it's not streaming currently by default, would you need the default value of done=true on the response too?

**Comment by jonmeredith** [comment]
I think it is streaming by default - or at least, that's how the protocol looks.  If we merge this then we'll have to modify the server to respect it.  As a client could request no streaming, but the server will always stream.

**Comment by javajolt** [comment]
I'll verify on a few clients

**Comment by hmmr** [comment]
Sadly, no, it is not supported for TS list_keys: https://github.com/basho/riak_kv/blob/end-to-end/timeseries/src/riak_client.erl#L655-L664 (there's no corresponding `stream_list_keys`. Something to raise a ticket about (or re-open RTS-203).

**Comment by jonmeredith** [comment]
Ah, so the protocol has support for it, but the server-side implementation is single-message with done always set. @alexmoore @bkerley do the clients expect a streaming response currently?

**Comment by alexmoore** [comment]
@jonmeredith The ones that have it implemented [appear to support the streaming](https://github.com/basho/riak-erlang-client/pull/249/files#diff-6f3df37226857a5dc67481e3fa68ef6aR156)

**Comment by javajolt** [comment]
@alexmoore Which ones do? Sounds like Erlang doesn't.

**Comment by alexmoore** [comment]
@javajolt It supports multiple response chunks and looking for a done message on the erlang client (see link in last post), but it just collects it all before returning, so it supports it on the network interface side at least.

**Comment by gcymbalski** [comment]
@borshop retest

**Comment by gcymbalski** [comment]
@borshop: retest

**Comment by gcymbalski** [comment]
@borshop: retry 7344d74

**Comment by hmmr** [comment]
@borshop merge

**Comment by javajolt** [comment]
From the mouth of @jonmeredith: "we should revert #168 don't need it"

**Pull request closed without merging**
