### PR TITLE
add gsets support [JIRA: RIAK-2690]

### PR DESCRIPTION
**Pull request by binarytemple-bet365**
@russelldb corrected P/R to add gset support 

basho/riak_kv#1437

### CODE REVIEW

**Comment by bashopatricia** [comment]
create jira issue

**Comment by DSomogyi** [comment]
create jira issue

**Comment by DSomogyi** [comment]
create jira issue

**Comment by lukebakken** [comment]
I spent some time throwing together a solution that would re-use existing message fields and not duplicate code. Basically, on `DtUpdateReq` it requires the addition of a `is_gset` boolean. Pretty much that and the addition of the `GSET` type is all that is necessary. `gset` values would be returned in `set_value` and the `type` field of `DtFetchResp` would be used to determine the type of `set_value`. Having both a `type` discriminator and two different fields for that type is redundant.

@zeeshanlakhani @russelldb @binarytemple-bet365 thoughts?

**Comment by zeeshanlakhani** [comment]
@lukebakken got a commit/gist to look at?

**Comment by lukebakken** [comment]
@zeeshanlakhani @binarytemple-bet365 see #204

**Comment by binarytemple-bet365** [comment]
@zeeshanlakhani @russelldb @lukebakken - I think it seems brittle. OTOH - I stand here in the role of supplicant before this temple of code. Let me know your decision and I'll comply.

**Comment by binarytemple-bet365** [comment]
Here's a diff comparison for convenience : [https://github.com/bet365/riak_pb/compare/feature/gsets...basho:features/lrb/add-gset-support](https://github.com/bet365/riak_pb/compare/feature/gsets...basho:features/lrb/add-gset-support)

**Comment by lukebakken** [comment]
I closed my PR after reading the scroll back in the room.

Having a `GSET` discriminator and `gset_value` field is redundant. I would like to see `gset_value` removed. You're only every going to return one thing that is a set (no matter how many different sets are implemented), and the one field suffices.

**Pull request closed without merging**
