### PR TITLE
initial gorpb look - addresses #71

### PR DESCRIPTION
**Pull request by boj**
This required me to add `package riak_pb;` to each *.proto file, which could very well cause a conflict.  Thoughts?

[Review on Reviewable](https://reviewable.io/reviews/basho/riak_pb/90)

### CODE REVIEW

**Comment by alexmoore** [comment]
@lukebakken Can you review this?

**Comment by lukebakken** [comment]
The go client brings in `riak_pb` via a submodule. Something I would like each client to do rather than gen code here.

**Comment by lukebakken** [comment]
There is a target in the `Makefile` to gen the go code from the proto files & the generated code is checked in. Works great.

**Comment by alexmoore** [comment]
@boj Thanks for the PR, it seems like it got lost for a while.  We have an alternative in place so I'm going to close this.

**Pull request closed without merging**
