### PR TITLE
split ts-related messaged into own .proto file

### PR DESCRIPTION
**Pull request by hmmr**

### CODE REVIEW

**Comment by lukebakken** [comment]
+1 388c5fddff980ec68b608442fce7d66b0db9560b

**Comment by lukebakken** [comment]
Good question @javajolt (shrug). Can you answer @hmmr ? thanks

**Comment by hmmr** [comment]
They come from ephemeral .erl files generated by protoc from .proto files. No way to fix them, hence they are to be ignored outright.

**Comment by lukebakken** [comment]
Sounds good to me. Now we just wait for the tests...

**Comment by javajolt** [comment]
@hmmr I was wondering about the 58 you deleted, not the additional ones...

**Comment by hmmr** [comment]
There's a nifty regexp-work happening behind the scenes (in tools.mk). Thus a bare file name (which I added) suppresses all dialyzer warnings coming from that file.

**Comment by javajolt** [comment]
Makes sense, @hmmr. Thanks.

**Pull request merged**
