### PR TITLE
Bucket Types API

### PR DESCRIPTION
**Pull request by lukebakken**
See original PR #115

### CODE REVIEW

**Comment by binarytemple-bet365** [comment]
OK. This P/R failed because the R14 tests failed. Is it necessary for this new feature to be supported by R14?

**Comment by lukebakken** [comment]
We've dropped `R14` from `develop`. I'll merge that in here.

**Comment by mitchellwrosen** [comment]
@lukebakken, any chance this might still happen?

**Comment by lukebakken** [comment]
Maybe ¯\_(ツ)_/¯

All of the PRs are still open and need review.

**Pull request closed without merging**
