### PR TITLE
Floating-point types for TsCells

### PR DESCRIPTION
**Pull request by bkerley**

### CODE REVIEW

**Comment by alexmoore** [comment]
In riak_pb_ts_codec.erl, do you need to implement `encode_field_type` for `float` or `double`?

**Comment by alexmoore** [comment]
Ok, looks like we use `encode_field_type` when creating the columntypes for a request response:
https://github.com/basho/riak_kv/blob/end-to-end/timeseries/src/riak_kv_pb_timeseries.erl#L300

**Comment by alexmoore** [comment]
@bkerley Could you review my merge / 1 line change ?

**Comment by alexmoore** [comment]
@javajolt  ^^

**Comment by javajolt** [comment]
`ts_basic` passes. What could go wrong?

**Comment by javajolt** [comment]
:+1: 0a8229b

**Comment by javajolt** [comment]
@borshop merge

**Pull request merged**
