### PR TITLE
Rename "binary" cells/columns to "varchar" to match recent changes. #156 [JIRA: RTS-557]

### PR DESCRIPTION
**Pull request by alexmoore**

### CODE REVIEW

**Comment by DSomogyi** [comment]
create jira issue

**Comment by lukebakken** [comment]
+1 dc91ed103f3257fd9338b7f5bf7fc9958bfb311d

**Comment by javajolt** [comment]
@borshop merge

**Comment by javajolt** [comment]
:+1: ef37353

**Comment by alexmoore** [comment]
@borshop merge

**Pull request merged**
