### PR TITLE
new pb messages and codes for TS delete op

### PR DESCRIPTION
**Pull request by hmmr**

### CODE REVIEW

**Comment by nickelization** [comment]
:+1: ecb7888cb7fe770362f0de21d25e2619fcaeb6af

**Comment by javajolt** [comment]
@hmmr Weren't you going to wait for @borshop?

**Comment by hmmr** [comment]
Well.. apparently I should have. No way to undo, it seems.

**Comment by javajolt** [comment]
@hmmr Next time...

**Pull request merged**
